import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "@/components/icon";
import { Reveal } from "@/components/animations";
import { Container, LinkButton, Section } from "@/components/ui";
import { cpdActivityGuide } from "@/lib/domain/cpd";

export const metadata: Metadata = {
  title: "CPD requirements",
  description: "A practical guide to Category A and Category B CPD activity formats, points and conditions.",
};

const sourceUrl = "https://www.legislation.gov.au/F2026L00244/asmade/text";

export default function CpdRequirementsPage() {
  return <>
    <section className="bg-[#fff8ef]"><Container className="py-20 sm:py-24"><div className="grid gap-12 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><p className="eyebrow text-[#a7472b]">The activity guide</p><h1 className="display mt-5 max-w-4xl text-5xl leading-[.95] text-[var(--forest)] sm:text-7xl">Know what counts before you book.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">The right CPD activity is easier to choose when the category, conditions and points are visible up front. Use this guide as a practical starting point, then check the current instrument for the requirements that apply to you.</p></div><div className="rounded-[1.4rem] border border-[#ecd8c2] bg-white p-6"><p className="eyebrow text-[#a7472b]">At a glance</p><div className="mt-6 grid grid-cols-2 gap-5"><div><p className="display text-4xl text-[var(--forest)]">2</p><p className="mt-1 text-sm text-[var(--muted)]">activity categories</p></div><div><p className="display text-4xl text-[var(--forest)]">4</p><p className="mt-1 text-sm text-[var(--muted)]">formats to choose from</p></div><div><p className="display text-4xl text-[var(--forest)]">1:1</p><p className="mt-1 text-sm text-[var(--muted)]">point-to-hour options</p></div><div><p className="display text-4xl text-[var(--forest)]">5</p><p className="mt-1 text-sm text-[var(--muted)]">points per accredited unit</p></div></div></div></div></Container></section>
    <Section className="bg-[#fbfaf6]"><Container><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-[var(--fern)]">Four ways to learn</p><h2 className="display mt-3 text-4xl text-[var(--forest)] sm:text-5xl">The conditions matter.</h2></div><a href={sourceUrl} target="_blank" rel="noreferrer" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-[var(--forest)] underline decoration-[#e87954] underline-offset-4">Read the source instrument <ArrowUpRight size={16} /></a></div><div className="mt-10 overflow-hidden rounded-[1.35rem] border border-[var(--line)] bg-white"><div className="hidden grid-cols-[.18fr_.72fr_1.1fr_.65fr] gap-6 border-b border-[var(--line)] bg-[var(--mist)] px-6 py-4 text-[10px] font-extrabold uppercase tracking-[.14em] text-[var(--muted)] md:grid"><span>Item</span><span>Activity</span><span>Conditions</span><span>Points</span></div>{cpdActivityGuide.map((item, index) => <Reveal key={item.number}><article id={`activity-${index + 1}`} className="grid gap-5 border-b border-[var(--line)] px-6 py-7 last:border-b-0 md:grid-cols-[.18fr_.72fr_1.1fr_.65fr] md:gap-6"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#fff0e8] text-xs font-black text-[#a7472b]">{item.number}</div><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[var(--muted)]">{item.category}</p><h3 className="mt-2 text-xl font-bold text-[var(--forest)]">{item.type}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.title}</p></div><div><p className="mb-2 text-[10px] font-extrabold uppercase tracking-[.14em] text-[var(--muted)] md:hidden">Conditions</p><p className="text-sm leading-6 text-[#52635d]">{item.detail}</p></div><div><p className="mb-2 text-[10px] font-extrabold uppercase tracking-[.14em] text-[var(--muted)] md:hidden">Points</p><p className="text-lg font-bold text-[#a7472b]">{item.rule}</p></div></article></Reveal>)}</div></Container></Section>
    <Section className="bg-[var(--forest)] text-white"><Container><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="eyebrow text-[#a9cfc0]">Keep your evidence together</p><h2 className="display mt-4 max-w-2xl text-4xl leading-[1.02] text-white sm:text-6xl">Choose the activity. Keep the record.</h2><p className="mt-6 max-w-xl text-base leading-7 text-[#c5d8ce]">Your registration captures the activity details, timing and CPD value. Create an account to keep your bookings and confirmations together.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/courses" className="bg-[#e87954] text-white hover:bg-[#f28c68]">Browse activities</LinkButton><LinkButton href="/register" variant="secondary" className="border-[#8caf9f] text-white hover:bg-[#2b5a50]">Register / sign in</LinkButton></div></div><div className="rounded-[1.35rem] border border-[#52786b] bg-[#214b43] p-6"><p className="eyebrow text-[#a9cfc0]">Important</p><p className="mt-4 text-sm leading-7 text-[#dce8e1]">This page is a plain-language summary of the supplied reference. It is not legal advice, a substitute for the current instrument, or a statement that every activity is approved for every practitioner.</p><a href={sourceUrl} target="_blank" rel="noreferrer" className="focus-ring mt-6 inline-flex items-center gap-2 text-sm font-bold text-white underline decoration-[#e87954] underline-offset-4">Open the official reference <ArrowUpRight size={15} /></a></div></div></Container></Section>
    <section className="border-t border-[var(--line)] bg-white"><Container className="flex flex-wrap items-center justify-between gap-5 py-8"><p className="text-sm text-[var(--muted)]">Have a question about which format suits your annual plan?</p><Link href="mailto:info@anzmigrationacademy.com" className="focus-ring text-sm font-bold text-[var(--forest)] underline decoration-[#e87954] underline-offset-4">Talk to the academy →</Link></Container></section>
  </>;
}
