import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "@/components/icon";
import { Reveal } from "@/components/animations";
import { Container, EmptyState, LinkButton, Section } from "@/components/ui";
import { getCategories, getCountries, getPublicSourceReferences, getPublishedActivityTypes } from "@/server/catalogue/queries";

export const metadata: Metadata = { title: "CPD catalogue guide", description: "Browse the database-backed CPD categories, activity types and source references maintained for the catalogue." };
export const dynamic = "force-dynamic";

export default async function CpdRequirementsPage() {
  let categories: Awaited<ReturnType<typeof getCategories>> = [];
  let countries: Awaited<ReturnType<typeof getCountries>> = [];
  let activityTypes: Awaited<ReturnType<typeof getPublishedActivityTypes>> = [];
  let sources: Awaited<ReturnType<typeof getPublicSourceReferences>> = [];
  try { [categories, countries, activityTypes, sources] = await Promise.all([getCategories(), getCountries(), getPublishedActivityTypes(), getPublicSourceReferences()]); } catch { categories = []; countries = []; activityTypes = []; sources = []; }
  const countryNames = new Map(countries.map((country) => [country.code, country.name]));
  const source = sources[0];
  return <>
    <section className="bg-[var(--signal-soft)]"><Container className="py-20 sm:py-24"><div className="grid gap-12 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><p className="eyebrow text-[var(--signal)]">The catalogue guide</p><h1 className="display mt-5 max-w-4xl text-5xl leading-[.95] text-[var(--forest)] sm:text-7xl">Know what is available before you book.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">Review the subjects, activity types and source references currently maintained in the catalogue database before choosing a class.</p></div><div className="rounded-[1.4rem] border border-[#e6cfc1] bg-[var(--surface)] p-6 shadow-[0_12px_40px_rgba(18,36,31,.04)]"><p className="eyebrow text-[var(--signal)]">At a glance</p><div className="mt-6 grid grid-cols-2 gap-5">{[[categories.length, "visible categories"], [activityTypes.length, "activity types"], [countries.length, "country contexts"], [sources.length, "source references"]].map(([value, label]) => <div key={String(label)}><p className="display text-4xl text-[var(--forest)]">{value}</p><p className="mt-1 text-sm text-[var(--muted)]">{label}</p></div>)}</div></div></div></Container></section>
    <Section className="bg-[var(--paper)]"><Container><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-[var(--fern)]">Database taxonomy</p><h2 className="display mt-3 text-4xl text-[var(--forest)] sm:text-5xl">The categories matter.</h2></div>{source ? <a href={source.url} target="_blank" rel="noreferrer" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-[var(--forest)] underline decoration-[var(--signal)] underline-offset-4">Read {source.title} <ArrowUpRight size={16} /></a> : null}</div>{categories.length ? <div className="mt-10 grid gap-4 md:grid-cols-2">{categories.map((category, index) => <Reveal key={category.id}><article className="card-lift rounded-[1.35rem] border border-[var(--line)] bg-[var(--surface)] p-6"><div className="flex items-start justify-between gap-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[var(--signal-soft)] text-xs font-black text-[var(--signal)]">{String(index + 1).padStart(2, "0")}</span><span className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[var(--muted)]">{countryNames.get(category.country) ?? category.country}</span></div><h3 className="mt-7 text-xl font-bold text-[var(--forest)]">{category.name}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{category.shortDescription ?? "This category is maintained for published catalogue classes."}</p><Link href={`/courses?country=${category.country}&category=${encodeURIComponent(category.slug)}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--forest)] underline decoration-[var(--signal)] underline-offset-4">View published classes <ArrowRight size={15} /></Link></article></Reveal>)}</div> : <div className="mt-10"><EmptyState title="No catalogue categories are available." description="Visible category records will appear here when they are added to the database." /></div>}</Container></Section>
    <Section className="bg-[var(--surface)]"><Container><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow text-[var(--fern)]">Activity types</p><h2 className="display mt-3 text-4xl text-[var(--forest)] sm:text-5xl">Choose the format that fits.</h2><p className="mt-5 max-w-md text-base leading-7 text-[var(--muted)]">Activity types come from published class records, so this list changes with the catalogue rather than a separate hardcoded guide.</p></div><div className="grid gap-3">{activityTypes.length ? activityTypes.map((activity) => <Link key={activity.value} href={`/courses?type=${encodeURIComponent(activity.value)}`} className="card-lift group flex items-center justify-between gap-5 rounded-xl border border-[var(--line)] bg-[var(--paper)] px-5 py-4"><span><strong className="block text-base text-[var(--forest)]">{activity.value}</strong><span className="mt-1 block text-xs text-[var(--muted)]">{activity.count} published {activity.count === 1 ? "class" : "classes"}</span></span><ArrowRight size={17} className="text-[var(--fern)] transition group-hover:translate-x-1" /></Link>) : <p className="rounded-xl border border-dashed border-[var(--line)] p-6 text-sm text-[var(--muted)]">No activity types are attached to published classes yet.</p>}</div></div></Container></Section>
    <Section className="bg-[var(--forest)] text-white"><Container><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="eyebrow text-[#a9cfc0]">Keep your evidence together</p><h2 className="display mt-4 max-w-2xl text-4xl leading-[1.02] text-white sm:text-6xl">Choose the activity. Keep the record.</h2><p className="mt-6 max-w-xl text-base leading-7 text-[#c5d8ce]">Your registration captures the class details, timing and CPD value stored for that record. Create an account to keep your bookings and confirmations together.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/courses" className="bg-[var(--signal)] text-white hover:bg-[#e88b6d]">Browse activities</LinkButton><LinkButton href="/register" variant="secondary" className="border-[#8caf9f] text-white hover:bg-[#2b5a50]">Register / sign in</LinkButton></div></div><div className="rounded-[1.35rem] border border-[#52786b] bg-[#214b43] p-6"><p className="eyebrow text-[#a9cfc0]">Important</p><p className="mt-4 text-sm leading-7 text-[#dce8e1]">Catalogue records are maintained by the academy. Check the linked source references and the requirements that apply to your own professional context before relying on a class for CPD purposes.</p>{source ? <a href={source.url} target="_blank" rel="noreferrer" className="focus-ring mt-6 inline-flex items-center gap-2 text-sm font-bold text-white underline decoration-[var(--signal)] underline-offset-4">Open the latest source reference <ArrowUpRight size={15} /></a> : null}</div></div></Container></Section>
  </>;
}
