import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getAdminSessionOrNull } from "@/server/auth/session";
import { Container } from "@/components/ui";
import { SignOutButton } from "@/components/auth-form";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { robots: { index: false, follow: false } };

export default async function AdminLayout({ children }: { children: React.ReactNode }) { const session = await getAdminSessionOrNull(); if (!session) redirect("/sign-in?next=/admin"); return <div className="min-h-[75vh] bg-[#edf2ef]"><Container className="grid gap-8 py-8 lg:grid-cols-[235px_1fr] lg:py-12"><aside className="rounded-[1.3rem] border border-[var(--line)] bg-[var(--forest)] p-4 text-[#dce8e1] lg:h-fit"><Link href="/admin" className="block px-3 text-sm font-bold tracking-[.08em] text-white">ANZ CPD <span className="text-[#d9a66b]">/</span> Admin</Link><p className="mt-2 px-3 text-xs text-[#a9c2b7]">Operational workspace</p><nav className="mt-7 grid gap-1 text-sm"><Link href="/admin" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Overview</Link><Link href="/admin/classes" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Classes</Link><Link href="/admin/categories" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Categories</Link><Link href="/admin/presenters" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Presenters</Link><Link href="/admin/source-references" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Source references</Link><Link href="/admin/bookings" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Bookings</Link><Link href="/admin/customers" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Customers</Link><Link href="/admin/payments" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Payments</Link><Link href="/admin/refunds" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Refunds</Link><Link href="/admin/audit-log" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Audit log</Link><Link href="/admin/settings" className="rounded-lg px-3 py-2 hover:bg-[#2b5a50] hover:text-white">Settings</Link><div className="mt-4 border-t border-[#35574f] pt-4 px-3"><SignOutButton /></div></nav></aside><div className="min-w-0">{children}</div></Container></div>; }
