import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "@/components/icon";
import { CourseCard } from "@/components/course-card";
import { Reveal } from "@/components/animations";
import { ClassCard, Container, LinkButton, Section } from "@/components/ui";
import { featuredCourses } from "@/lib/domain/cpd";
import { getPublishedClasses } from "@/server/catalogue/queries";

export const dynamic = "force-dynamic";

type SearchParams = Promise<{ category?: string; type?: string; country?: string }>;

export default async function CoursesPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const category = params.category === "Category A" || params.category === "Category B" ? params.category : undefined;
  const type = params.type;
  const country = params.country;
  const courses = featuredCourses.filter((course) => (!category || course.category === category) && (!type || course.type === type) && (!country || course.country.includes(country)));
  let liveClasses: Awaited<ReturnType<typeof getPublishedClasses>> = [];
  try { liveClasses = await getPublishedClasses({ time: "upcoming", pageSize: 12 }); } catch { liveClasses = []; }
  const clearHref = "/courses";
  const typeLinks = ["Workshop", "Accredited unit", "Conference, seminar or lecture", "Private study with assessment"];

  return <>
    <section className="bg-[var(--forest)] text-white"><Container className="py-20 sm:py-24"><div className="max-w-4xl"><p className="eyebrow text-[#b9d6c7]">The catalogue</p><h1 className="display mt-5 text-5xl leading-[.95] sm:text-7xl">Choose the kind of learning you need next.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#c5d8ce]">Every activity shows its category, format, hours, points, date and presenter before you register. Use the filters to find a better fit.</p></div><div className="mt-10 flex flex-wrap gap-2 text-xs font-bold"><Link href="/courses" className={`rounded-full px-4 py-2.5 ${!category && !type && !country ? "bg-[#e87954] text-white" : "border border-[#6f9588] text-[#dce8e1]"}`}>All activities</Link><Link href="/courses?category=Category%20A" className={`rounded-full px-4 py-2.5 ${category === "Category A" ? "bg-[#e87954] text-white" : "border border-[#6f9588] text-[#dce8e1]"}`}>Category A</Link><Link href="/courses?category=Category%20B" className={`rounded-full px-4 py-2.5 ${category === "Category B" ? "bg-[#e87954] text-white" : "border border-[#6f9588] text-[#dce8e1]"}`}>Category B</Link><Link href="/courses?country=Australia" className={`rounded-full px-4 py-2.5 ${country === "Australia" ? "bg-[#e87954] text-white" : "border border-[#6f9588] text-[#dce8e1]"}`}>Australia</Link><Link href="/courses?country=New%20Zealand" className={`rounded-full px-4 py-2.5 ${country === "New Zealand" ? "bg-[#e87954] text-white" : "border border-[#6f9588] text-[#dce8e1]"}`}>New Zealand</Link></div></Container></section>
    <Section className="bg-[#fbfaf6]"><Container><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-[var(--fern)]">{courses.length} activities</p><h2 className="display mt-3 text-4xl text-[var(--forest)] sm:text-5xl">Upcoming CPD</h2></div><Link href="/cpd-requirements" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-[var(--forest)] underline decoration-[#e87954] underline-offset-4">Compare activity rules <ArrowUpRight size={16} /></Link></div><div className="mt-7 flex flex-wrap gap-2 border-y border-[var(--line)] py-4 text-xs font-semibold"><span className="mr-2 py-2 text-[var(--muted)]">Filter by type:</span>{typeLinks.map((item) => <Link key={item} href={`/courses?type=${encodeURIComponent(item)}${category ? `&category=${encodeURIComponent(category)}` : ""}`} className={`rounded-full px-3 py-2 ${type === item ? "bg-[var(--forest)] text-white" : "bg-white text-[var(--muted)] hover:text-[var(--forest)]"}`}>{item}</Link>)}{category || type || country ? <Link href={clearHref} className="ml-auto py-2 font-bold text-[#a7472b] underline underline-offset-4">Clear filters</Link> : null}</div>{courses.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{courses.map((course) => <Reveal key={course.slug}><CourseCard course={course} /></Reveal>)}</div> : <div className="mt-8 rounded-[1.35rem] border border-dashed border-[var(--line)] bg-white p-12 text-center"><h2 className="display text-3xl text-[var(--forest)]">No activities match those filters.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[var(--muted)]">Try a different activity type or clear the filters to see the full programme.</p><Link href={clearHref} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[var(--forest)] underline underline-offset-4">Show all activities <ArrowRight size={15} /></Link></div>}</Container></Section>
    {liveClasses.length ? <Section className="bg-[var(--mist)]"><Container><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-[var(--fern)]">Secure registration</p><h2 className="display mt-3 text-4xl text-[var(--forest)]">Book an opened date.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--muted)]">These are the dates currently open in the secure booking catalogue. Payment is handled through Stripe Checkout.</p></div><LinkButton href="/classes" variant="secondary">Open all live dates <ArrowRight className="ml-2" size={16} /></LinkButton></div><div className="mt-9 grid gap-5 lg:grid-cols-3">{liveClasses.slice(0, 3).map((item) => <Reveal key={item.id}><ClassCard item={item} /></Reveal>)}</div></Container></Section> : <section className="border-y border-[#eadfd2] bg-[#fff8ef]"><Container className="flex flex-wrap items-center justify-between gap-6 py-8"><p className="max-w-2xl text-sm leading-6 text-[#6f5b4e]">Need a date for your team? Contact the academy and we can help you plan a CPD pathway around the requirements that apply to you.</p><a href="mailto:info@anzmigrationacademy.com" className="focus-ring rounded-full border border-[#b77b3f] px-5 py-3 text-sm font-bold text-[#85551e] hover:bg-[#fbead4]">Contact the academy</a></Container></section>}
  </>;
}
