import Link from "next/link";
import { ClassCard, Container, EmptyState, LinkButton, Section } from "@/components/ui";
import { getCategories, getPublishedClasses } from "@/server/catalogue/queries";
export const dynamic = "force-dynamic";
export default async function HomePage() {
  let classes: Awaited<ReturnType<typeof getPublishedClasses>> = [];
  let categories: Awaited<ReturnType<typeof getCategories>> = [];
  let unavailable = false;
  try { [classes, categories] = await Promise.all([getPublishedClasses({ time: "upcoming", pageSize: 3 }), getCategories()]); } catch { unavailable = true; }
  return <>
    <section className="academy-hero"><Container className="grid items-center gap-12 py-16 lg:grid-cols-[1.3fr_.7fr] lg:py-24">
      <div><p className="eyebrow text-[var(--forest)]">Professional learning. Practical confidence.</p><h1 className="display mt-6 max-w-3xl text-[var(--forest)]">Stay informed.<br />Move your<br /><em>practice forward.</em></h1><p className="mt-7 max-w-lg text-base leading-7 text-[var(--muted)]">Continuing professional development for migration agents and immigration advisers across Australia and New Zealand.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/classes" size="lg">Explore CPD activities ↗</LinkButton><LinkButton href="/australia" variant="quiet">Choose a country</LinkButton></div><p className="mt-8 text-xs text-[var(--muted)]">Clear activity details · Secure checkout · Your booking records together</p></div>
      <div className="space-y-4"><p className="eyebrow text-[var(--muted)]">Learning for your practice</p><Link href="/australia" className="pathway-card"><span className="text-xs font-bold tracking-widest text-[var(--fern)]">01 / AUSTRALIA</span><strong className="display">Australian migration practice ↗</strong><p>Explore activities for migration professionals practising in Australia.</p></Link><Link href="/new-zealand" className="pathway-card"><span className="text-xs font-bold tracking-widest text-[var(--fern)]">02 / NEW ZEALAND</span><strong className="display">New Zealand immigration advice ↗</strong><p>Find professional learning for licensed immigration advisers.</p></Link><p className="px-1 text-xs leading-5 text-[var(--muted)]">Choose your professional context. Check each activity’s CPD value and suitability before booking.</p></div>
    </Container></section>
    <Section><Container><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-[var(--fern)]">Make time for what matters</p><h2 className="display mt-3 text-4xl sm:text-5xl">Your next learning opportunity.</h2></div><LinkButton href="/classes" variant="secondary">View all activities ↗</LinkButton></div><div className="mt-9">{classes.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{classes.map(item => <ClassCard key={item.id} item={item} />)}</div> : <EmptyState eyebrow={unavailable ? "Catalogue unavailable" : "Upcoming programme"} title={unavailable ? "We couldn’t load the latest activities." : "New dates are on their way."} description={unavailable ? "Please try the catalogue again shortly. You can still explore the guide or contact the academy." : "Published activities will appear here when new dates are available. Explore the guide while you plan your next step."} action={<LinkButton href={unavailable ? "/classes" : "/cpd-requirements"} variant="secondary">{unavailable ? "Try the catalogue" : "Explore the CPD guide"}</LinkButton>} />}</div></Container></Section>
    <Section className="border-y border-[var(--line)] bg-white"><Container className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[var(--fern)]">Find your focus</p><h2 className="display mt-4 text-4xl sm:text-5xl">Relevant to the<br />work you do.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-[var(--muted)]">Start with a topic, then compare the presenter, schedule, delivery format and CPD value.</p></div><div className="divide-y divide-[var(--line)]">{categories.length ? categories.slice(0, 6).map((category, i) => <Link key={category.id} href={`/classes?country=${category.country}&category=${encodeURIComponent(category.slug)}`} className="group flex items-center gap-5 py-5"><span className="text-xs text-[var(--muted)]">{String(i + 1).padStart(2, "0")}</span><span className="flex-1"><strong className="block text-lg font-medium">{category.name}</strong><span className="mt-1 block text-xs text-[var(--muted)]">{category.country === "AU" ? "Australia" : "New Zealand"}</span></span><span className="text-xl group-hover:translate-x-1" aria-hidden="true">↗</span></Link>) : <div className="py-6"><h3 className="text-lg font-semibold">A clearer place to start</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Understand the catalogue categories, activity formats and source references.</p><LinkButton href="/cpd-requirements" variant="quiet" className="mt-4">Read the guide ↗</LinkButton></div>}</div></Container></Section>
    <Section className="bg-[var(--mist)]"><Container><p className="eyebrow text-[var(--fern)]">From finding an activity to keeping the record</p><h2 className="display mt-4 text-4xl sm:text-5xl">Professional development. Less admin.</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{[["01", "Choose with confidence", "Compare the country, CPD value, presenter and local timezone before you book."], ["02", "Reserve your place", "Book as a guest or choose an account. Complete payment securely with Stripe."], ["03", "Keep the details close", "Use your secure booking link or account to find your booking and attendance details."]].map(([number, title, text]) => <div key={number} className="border-t border-[var(--color-border-strong)] pt-6"><span className="text-xs font-bold text-[var(--fern)]">{number}</span><h3 className="mt-4 text-xl font-medium">{title}</h3><p className="mt-3 max-w-sm text-sm leading-7 text-[var(--muted)]">{text}</p></div>)}</div></Container></Section>
  </>;
}
