"use client";

import { useActionState, useState } from "react";
import { useRouter } from "next/navigation";
import { Field, FormNotice, TextInput } from "@/components/ui";
import { cancelPendingBookingAction } from "@/server/actions/customer";

export function AccountSetupForm({ token }: { token?: string }) {
  const router = useRouter();
  const [state, setState] = useState<{ error?: string; success?: string; loading?: boolean }>({});
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setState({ loading: true }); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch("/api/account/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) setState({ error: result.error ?? "Account setup failed." }); else { setState({ success: result.message }); window.setTimeout(() => router.push("/sign-in"), 1200); } } catch { setState({ error: "We could not reach the service. Try again." }); } }
  return <form onSubmit={submit} className="space-y-5"><input type="hidden" name="token" value={token ?? ""} /><FormNotice>{state.error}</FormNotice><FormNotice tone="success">{state.success}</FormNotice><Field label="Name" required><TextInput name="name" autoComplete="name" required /></Field><Field label="Password" hint="Use at least 12 characters." required><TextInput name="password" type="password" autoComplete="new-password" minLength={12} required /></Field><Field label="Confirm password" required><TextInput name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required /></Field><button disabled={state.loading || !token} className="focus-ring min-h-12 w-full rounded-full bg-[var(--forest)] px-5 text-sm font-bold text-white disabled:opacity-60">{state.loading ? "Setting up account…" : "Set up account"}</button></form>;
}

export function ClaimForm({ token }: { token: string }) { const [state, setState] = useState<{ error?: string; success?: string }>({}); async function submit() { const response = await fetch("/api/account/claim", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token }) }); const result = await response.json(); setState(response.ok ? { success: `Connected ${result.linked} booking record${result.linked === 1 ? "" : "s"}.` } : { error: result.error ?? "Records could not be connected." }); } return <div className="space-y-5"><FormNotice>{state.error}</FormNotice><FormNotice tone="success">{state.success}</FormNotice><button onClick={() => void submit()} className="focus-ring min-h-12 w-full rounded-full bg-[var(--forest)] px-5 text-sm font-bold text-white">Connect booking records</button></div>; }

export function ClaimRequestForm() { const [state, setState] = useState<{ error?: string; success?: string; loading?: boolean }>({}); async function submit() { setState({ loading: true }); try { const response = await fetch("/api/account/claim/request", { method: "POST" }); const result = await response.json(); setState(response.ok ? { success: result.message } : { error: result.error ?? "The claim link could not be sent." }); } catch { setState({ error: "We could not reach the service. Try again later." }); } } return <div className="space-y-5"><FormNotice>{state.error}</FormNotice><FormNotice tone="success">{state.success}</FormNotice><button onClick={() => void submit()} disabled={state.loading} className="focus-ring min-h-12 w-full rounded-full bg-[var(--forest)] px-5 text-sm font-bold text-white disabled:opacity-60">{state.loading ? "Sending…" : "Email me a secure claim link"}</button></div>; }

export function CancelBookingForm({ bookingId }: { bookingId: string }) { const [state, action, pending] = useActionState(async (_state: { ok: boolean; error?: string; message?: string }, formData: FormData) => cancelPendingBookingAction(formData), { ok: false } as { ok: boolean; error?: string; message?: string }); return <form action={action} className="space-y-2"><input type="hidden" name="bookingId" value={bookingId} />{state.error ? <FormNotice>{state.error}</FormNotice> : null}<button disabled={pending} className="focus-ring rounded-full border border-[#e8bbb6] px-5 py-3 text-sm font-bold text-[var(--error)] hover:bg-[#fff0ee]" type="submit">{pending ? "Cancelling…" : "Cancel unpaid booking"}</button></form>; }
