import { ClassCard, Container, EmptyState, LinkButton, PageIntro, Section } from "@/components/ui";
import { getPublishedClasses } from "@/server/catalogue/queries";

export const dynamic = "force-dynamic";

export default async function AustraliaPage() {
  let unavailable = false;
  let classes: Awaited<ReturnType<typeof getPublishedClasses>> = [];
  try { classes = await getPublishedClasses({ country: "AU", time: "upcoming", pageSize: 6 }); } catch { classes = []; unavailable = true; }
  return <><section className="bg-[var(--mist)]"><Container className="py-12 sm:py-16"><PageIntro eyebrow="Australia · AU" title="Professional development for Australian migration practice." description="Topics are organised around the responsibilities of registered migration agents: ethical standards, the Code of Conduct, evidence, compliance and the practical pathways clients ask about."><div className="flex flex-wrap gap-3"><LinkButton href="/classes?country=AU">Browse Australia classes</LinkButton><LinkButton href="/classes?country=AU&time=past" variant="secondary">View past classes</LinkButton></div></PageIntro></Container></section><Section className="bg-[var(--paper)]"><Container><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[var(--fern)]">Country context</p><h2 className="display mt-4 text-4xl text-[var(--forest)]">Points, obligations, evidence.</h2></div><p className="max-w-2xl text-base leading-7 text-[var(--muted)]">Australian activities are represented with CPD points where supplied by the provider. ANZ CPD does not mark development activities as OMARA-approved or make claims about registration outcomes. Always check the current requirements and source material maintained by your organisation.</p></div>{classes.length ? <div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{classes.map((item) => <ClassCard key={item.id} item={item} />)}</div> : <div className="mt-12"><EmptyState title={unavailable ? "We couldn’t load this information." : "No upcoming Australian classes are currently published."} description={unavailable ? "Please try again shortly, or contact the academy for help." : "Check back for new CPD dates or browse the full catalogue while the next sessions are prepared."} action={<LinkButton href="/classes" variant="secondary">Browse the catalogue</LinkButton>} /></div>}</Container></Section></>;
}
