import { ClassCard, Container, LinkButton, Section } from "@/components/ui";
import { getPublishedClasses } from "@/server/catalogue/queries";

export const dynamic = "force-dynamic";

export default async function AustraliaPage() {
  let classes: Awaited<ReturnType<typeof getPublishedClasses>> = [];
  try { classes = await getPublishedClasses({ country: "AU", time: "upcoming", pageSize: 6 }); } catch { classes = []; }
  return <><Section className="bg-[var(--mist)]"><Container><p className="eyebrow text-[var(--fern)]">Australia · AU</p><h1 className="display mt-5 max-w-4xl text-5xl leading-[.98] text-[var(--forest)] sm:text-7xl">Professional development for Australian migration practice.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">Topics are organised around the responsibilities of registered migration agents: ethical standards, the Code of Conduct, evidence, compliance and the practical pathways clients ask about.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/classes?country=AU">Browse Australia classes</LinkButton><LinkButton href="/classes?country=AU&time=past" variant="secondary">View past classes</LinkButton></div></Container></Section><Section><Container><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[var(--fern)]">Country context</p><h2 className="display mt-4 text-4xl text-[var(--forest)]">Points, obligations, evidence.</h2></div><p className="max-w-2xl text-base leading-7 text-[var(--muted)]">Australian activities are represented with CPD points where supplied by the provider. ANZ CPD does not mark development activities as OMARA-approved or make claims about registration outcomes. Always check the current requirements and source material maintained by your organisation.</p></div>{classes.length ? <div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{classes.map((item) => <ClassCard key={item.id} item={item} />)}</div> : <div className="mt-12 rounded-[1.5rem] border border-dashed border-[var(--line)] p-10 text-center text-sm text-[var(--muted)]">No upcoming Australian classes are currently published. Check back for new CPD dates.</div>}</Container></Section></>;
}
