import { ClassCard, Container, EmptyState, LinkButton, PageIntro, Section } from "@/components/ui";
import { getPublishedClasses } from "@/server/catalogue/queries";

export const dynamic = "force-dynamic";

export default async function NewZealandPage() {
  let unavailable = false;
  let classes: Awaited<ReturnType<typeof getPublishedClasses>> = [];
  try { classes = await getPublishedClasses({ country: "NZ", time: "upcoming", pageSize: 6 }); } catch { classes = []; unavailable = true; }
  return <><section className="bg-[var(--mist)]"><Container className="py-12 sm:py-16"><PageIntro eyebrow="New Zealand · NZ" title="Professional development for New Zealand immigration advice." description="Build a clearer reading practice around Immigration New Zealand instructions, residence and temporary entry matters, adviser obligations and the evidence that supports a sound application."><div className="flex flex-wrap gap-3"><LinkButton href="/classes?country=NZ">Browse New Zealand classes</LinkButton><LinkButton href="/classes?country=NZ&time=past" variant="secondary">View past classes</LinkButton></div></PageIntro></Container></section><Section className="bg-[var(--paper)]"><Container><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[var(--info)]">Country context</p><h2 className="display mt-4 text-4xl text-[var(--forest)]">Hours, instructions, judgment.</h2></div><p className="max-w-2xl text-base leading-7 text-[var(--muted)]">New Zealand activities are represented with CPD hours where supplied by the provider. ANZ CPD does not claim Immigration Advisers Authority approval or guarantee licensing outcomes. Immigration instructions and professional requirements can change.</p></div>{classes.length ? <div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{classes.map((item) => <ClassCard key={item.id} item={item} />)}</div> : <div className="mt-12"><EmptyState eyebrow="No live dates yet" title="No upcoming New Zealand classes are currently published." description={unavailable ? "Please try again shortly, or contact the academy for help." : "Check back for new CPD dates or browse the full catalogue while the next sessions are prepared."} action={<LinkButton href="/classes" variant="secondary">Browse the catalogue</LinkButton>} /></div>}</Container></Section></>;
}
