import { ClassCard, Container, LinkButton, Section } from "@/components/ui";
import { getPublishedClasses } from "@/server/catalogue/queries";

export const dynamic = "force-dynamic";

export default async function NewZealandPage() {
  let classes: Awaited<ReturnType<typeof getPublishedClasses>> = [];
  try { classes = await getPublishedClasses({ country: "NZ", time: "upcoming", pageSize: 6 }); } catch { classes = []; }
  return <><Section className="bg-[#f7f0e7]"><Container><p className="eyebrow text-[var(--ochre)]">New Zealand · NZ</p><h1 className="display mt-5 max-w-4xl text-5xl leading-[.98] text-[var(--forest)] sm:text-7xl">Professional development for New Zealand immigration advice.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">Build a clearer reading practice around Immigration New Zealand instructions, residence and temporary entry matters, adviser obligations and the evidence that supports a sound application.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/classes?country=NZ">Browse New Zealand classes</LinkButton><LinkButton href="/classes?country=NZ&time=past" variant="secondary">View past classes</LinkButton></div></Container></Section><Section><Container><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[var(--ochre)]">Country context</p><h2 className="display mt-4 text-4xl text-[var(--forest)]">Hours, instructions, judgment.</h2></div><p className="max-w-2xl text-base leading-7 text-[var(--muted)]">New Zealand activities are represented with CPD hours where supplied by the provider. ANZ CPD does not claim Immigration Advisers Authority approval or guarantee licensing outcomes. Immigration instructions and professional requirements can change.</p></div>{classes.length ? <div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{classes.map((item) => <ClassCard key={item.id} item={item} />)}</div> : <div className="mt-12 rounded-[1.5rem] border border-dashed border-[var(--line)] p-10 text-center text-sm text-[var(--muted)]">No upcoming New Zealand classes are currently published. Check back for new CPD dates.</div>}</Container></Section></>;
}
