import Link from "next/link";
import { Button, ClassCard, Container, EmptyState, Field, LinkButton, PageIntro, Pagination, Section, Select, TextInput } from "@/components/ui";
import { getCategories, getPublishedActivityTypes, getPublishedClasses } from "@/server/catalogue/queries";
export const dynamic = "force-dynamic";
type Params = { country?: string; category?: string; delivery?: string; time?: string; type?: string; q?: string; page?: string };
export default async function ClassesPage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams;
  const country = params.country === "AU" || params.country === "NZ" ? params.country : undefined;
  const delivery = params.delivery === "ONLINE" || params.delivery === "IN_PERSON" || params.delivery === "HYBRID" ? params.delivery : undefined;
  const time = params.time === "past" ? "past" : "upcoming";
  const page = Math.min(10000, Math.max(1, Math.floor(Number(params.page) || 1)));
  let categories: Awaited<ReturnType<typeof getCategories>> = [];
  let types: Awaited<ReturnType<typeof getPublishedActivityTypes>> = [];
  let classes: Awaited<ReturnType<typeof getPublishedClasses>> = [];
  let unavailable = false;
  try { [categories, types, classes] = await Promise.all([getCategories(country), getPublishedActivityTypes(country), getPublishedClasses({ country, categorySlug: params.category, activityType: params.type, deliveryFormat: delivery, time, search: params.q, page })]); } catch { unavailable = true; }
  const href = (changes: Partial<Record<keyof Params, string | undefined>>) => { const query = new URLSearchParams(); for (const [key, value] of Object.entries({ ...params, ...changes })) if (value) query.set(key, value); return `/classes${query.size ? `?${query}` : ""}`; };
  const filters = [["country", country === "AU" ? "Australia" : country === "NZ" ? "New Zealand" : undefined], ["category", params.category], ["delivery", delivery?.replaceAll("_", " ").toLowerCase()], ["type", params.type], ["q", params.q]] as const;
  return <><section className="border-b border-[var(--line)] bg-[var(--mist)]"><Container className="py-12 sm:py-16"><PageIntro eyebrow="The CPD catalogue" title="Learning that moves you forward." description="Find professional development for your practice. Compare the topic, CPD value and schedule, then choose your next activity." /></Container></section>
    <Section className="!py-10"><Container><div className="grid items-start gap-8 lg:grid-cols-[250px_1fr]"><aside className="rounded-xl border border-[var(--line)] bg-white p-5 lg:sticky lg:top-32"><form method="get" className="space-y-5"><input type="hidden" name="time" value={time} /><Field label="Search activities"><TextInput name="q" type="search" placeholder="Topic or keyword" defaultValue={params.q} /></Field><details open><summary className="mb-5 cursor-pointer text-sm font-semibold">Refine your search</summary><div className="space-y-5"><Field label="Professional context"><Select name="country" defaultValue={country ?? ""}><option value="">Australia & New Zealand</option><option value="AU">Australia</option><option value="NZ">New Zealand</option></Select></Field><Field label="Category"><Select name="category" defaultValue={params.category ?? ""}><option value="">All categories</option>{categories.map(item => <option key={item.id} value={item.slug}>{item.name}</option>)}</Select></Field><Field label="Activity type"><Select name="type" defaultValue={params.type ?? ""}><option value="">All types</option>{types.map(item => <option key={item.value} value={item.value}>{item.value}</option>)}</Select></Field><Field label="Delivery"><Select name="delivery" defaultValue={delivery ?? ""}><option value="">Any delivery</option><option value="ONLINE">Online</option><option value="IN_PERSON">In person</option><option value="HYBRID">Hybrid</option></Select></Field></div></details><Button type="submit" className="w-full">Apply filters</Button><Link href="/classes" className="block text-center text-xs font-semibold underline underline-offset-4">Reset filters</Link></form></aside>
    <div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[var(--line)] pb-5"><nav aria-label="Activity dates" className="flex gap-1 rounded-lg bg-[var(--mist)] p-1">{(["upcoming", "past"] as const).map(value => <Link key={value} href={href({ time: value, page: undefined })} aria-current={time === value ? "page" : undefined} className={`rounded-md px-5 py-2.5 text-sm font-semibold ${time === value ? "bg-white shadow-sm" : "text-[var(--muted)]"}`}>{value === "past" ? "Past activities" : "Upcoming"}</Link>)}</nav><p className="text-xs text-[var(--muted)]">{unavailable ? "Results unavailable" : `${classes.length} activities on this page`}</p></div><div className="my-5 flex flex-wrap gap-2">{filters.map(([key, label]) => label ? <Link key={key} href={href({ [key]: undefined, page: undefined })} aria-label={`Remove filter: ${label}`} className="rounded-full border border-[var(--line)] bg-white px-3 py-1.5 text-xs">{label} <span aria-hidden="true" className="ml-2">×</span></Link> : null)}</div>
    {classes.length ? <div className="grid gap-5 md:grid-cols-2">{classes.map(item => <ClassCard key={item.id} item={item} />)}</div> : <EmptyState eyebrow={unavailable ? "Please try again" : "Your search"} title={unavailable ? "The catalogue is temporarily unavailable." : "No activities match this selection."} description={unavailable ? "We couldn’t retrieve the latest listings. Please retry shortly or contact the academy for help." : "Try another topic, broaden your filters or check back for new dates."} action={<LinkButton href={unavailable ? href({}) : "/classes"} variant="secondary">{unavailable ? "Try again" : "Clear filters"}</LinkButton>} />}
    <Pagination page={page} hasNext={classes.length === 12} previousHref={href({ page: String(page - 1) })} nextHref={href({ page: String(page + 1) })} /></div></div></Container></Section></>;
}
